// examples/react-basic/src/pages/About.tsx
export default function About() {
  return (
    <>
      <div className="card">
        <h2 style={{ marginBottom: '0.5rem' }}>About</h2>
        <p style={{ color: '#94a3b8', lineHeight: 1.6 }}>
          This example app is instrumented with <strong>@tindalabs/blindspot-react</strong>.
          It records route navigations via <code>&lt;BlindspotRoutes&gt;</code>, user interactions,
          form submissions, fetch calls, and web vitals — all as OpenTelemetry spans, without
          capturing any personally identifiable information.
        </p>
      </div>
      <div className="card">
        <h3 style={{ marginBottom: '0.75rem' }}>Stack</h3>
        <ul style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
          <li><strong>SDK</strong> → @tindalabs/blindspot-react (this repo)</li>
          <li><strong>Router</strong> → React Router v6 + BlindspotRoutes</li>
          <li><strong>Collector</strong> → OpenTelemetry Collector Contrib (localhost:4318)</li>
          <li><strong>Storage</strong> → Grafana Tempo</li>
          <li><strong>Visualization</strong> → Grafana (localhost:3100)</li>
        </ul>
      </div>
    </>
  );
}

// examples/vue-basic/src/pages/About.vue
<template>
  <div class="card">
    <h2 style="margin-bottom: 0.5rem">About</h2>
    <p style="color: #94a3b8; line-height: 1.6">
      This example app is instrumented with <strong>@tindalabs/blindspot-vue</strong>.
      It records route navigations via <code>installBlindspotRouter</code>, user interactions,
      form submissions, fetch calls, and web vitals — all as OpenTelemetry spans, without
      capturing any personally identifiable information.
    </p>
  </div>
  <div class="card">
    <h3 style="margin-bottom: 0.75rem">Stack</h3>
    <ul style="list-style: none; display: flex; flex-direction: column; gap: 0.5rem">
      <li><strong>SDK</strong> → @tindalabs/blindspot-vue (this repo)</li>
      <li><strong>Router</strong> → Vue Router 4 + installBlindspotRouter</li>
      <li><strong>Collector</strong> → OpenTelemetry Collector Contrib (localhost:4318)</li>
      <li><strong>Storage</strong> → Grafana Tempo</li>
      <li><strong>Visualization</strong> → Grafana (localhost:3100)</li>
    </ul>
  </div>
</template>
